import Link from "next/link";
import { ArrowLeft, Shield } from "lucide-react";

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-surface-0 py-12 px-4 sm:px-6">
      <div className="max-w-3xl mx-auto">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-sm text-text-muted hover:text-text-primary transition-colors mb-8"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>

        <div className="glass rounded-3xl p-8 sm:p-12">
          <div className="flex items-center gap-3 mb-6">
            <div className="w-10 h-10 rounded-xl gradient-bg flex items-center justify-center">
              <Shield className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-3xl font-bold">Terms of Service</h1>
          </div>

          <p className="text-sm text-text-muted mb-8">
            Last Updated: {new Date().toLocaleDateString("en-US", { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>

          <div className="space-y-8 text-text-secondary leading-relaxed">
            <section>
              <h2 className="text-xl font-bold text-text-primary mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using GrowMyAccount AI (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-text-primary mb-3">2. AI Liability and Disclaimers</h2>
              <div className="bg-brand-500/10 border border-brand-500/20 rounded-xl p-5 text-text-primary">
                <p className="font-semibold mb-2">CRITICAL DISCLAIMER REGARDING AI INSIGHTS:</p>
                <p className="text-sm">
                  All insights, recommendations, strategies, and analytics generated by GrowMyAccount AI are provided for <strong>informational and educational purposes only</strong>. We make absolutely no guarantees or warranties regarding Instagram account growth, increased engagement, or financial gain resulting from the use of our service.
                </p>
                <p className="text-sm mt-3">
                  Furthermore, GrowMyAccount AI and its operators shall <strong>not be held liable</strong> for any negative consequences resulting from following the AI&apos;s advice, including but not limited to: account shadowbans, account suspensions, loss of followers, decreased engagement, or loss of revenue. You are solely responsible for ensuring that your actions on Instagram comply with Meta&apos;s official Terms of Service and Community Guidelines.
                </p>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-bold text-text-primary mb-3">3. Data Usage and Privacy</h2>
              <p>
                Our service accesses your Instagram data via the official Meta Graph API. We do not sell your data. We retain usage logs and a record of your connection solely for the purpose of providing the service and enforcing rate limits. Upon disconnecting your account via our platform, we immediately revoke our own access to your Meta access tokens.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-bold text-text-primary mb-3">4. Limitation of Liability</h2>
              <p>
                In no event shall GrowMyAccount AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
              </p>
            </section>
          </div>
        </div>
      </div>
    </main>
  );
}
